### PR TITLE
[RV64_DYNAREC] Added more opcodes for SV and some fixes

### PR DESCRIPTION
**Pull request by ksco**
Tested with SV.

### CODE REVIEW

**Comment by ksco** [comment]
Oh, something I should mention is that I noticed there are some `subpd` logs in ref17.txt, but there is no SUBPD opcode at all in the test17 binary file, is this expected?

**Comment by ptitSeb** [comment]
Compiler do what they want to optimize things...

**Comment by ksco** [comment]
Ok, but since we're testing the instruction itself, maybe we should consider turning off optimizations when compiling these tests?

**Comment by ptitSeb** [comment]
Sure. Fill free to build a new version if you can have a better one, with more opcodes tested :)

**Pull request merged**
