### PR TITLE
A few cosmetic fixes

### PR DESCRIPTION
**Pull request by julliard**
A few cosmetic fixes for things spotted while trying to do a PE build under Wine. These should all be no-ops.

### CODE REVIEW

**Comment by ptitSeb** [comment]
a PE build ... of box64? are you plugin box64 in wine peloader or something like that? removing elfloader and using something PE oriented instead?

**Comment by julliard** [comment]
What I'm trying to do is basically use only the emulator parts, and plug it into the existing wow64 support, so syscalls go to Wow64SystemServiceEx which takes care of 32->64 transitions, and Wine handles everything else on the 64-bit side.

**Comment by ptitSeb** [comment]
Nice.

Signals are also probably a bit tricky.

**Comment by theofficialgman** [comment]
> What I'm trying to do is basically use only the emulator parts, and plug it into the existing wow64 support, so syscalls go to Wow64SystemServiceEx which takes care of 32->64 transitions, and Wine handles everything else on the 64-bit side.

by that do you mean you trying to build wine on ARM64 with `--enable-archs=i386,x86_64.aarch64` so that the wine PE userspace is linux aarch64 (eg: wine lib folder looks like `aarch64-unix  aarch64-windows  i386-windows  x86_64-windows`) and you are using box64 for any/all x86/x64 binary recompilation only? I couldn't get that to work with wine/box64 as it is. wine would never call box64... it juser errored whenever it met x86/x64 code

**Comment by julliard** [comment]
> Signals are also probably a bit tricky too.

All we really need from the emulator is to fetch the current context, all signal handling is done on the Wine side. When the exception needs to be handled in 32-bit we reenter emulation through KiUserExceptionDispatcher. It seems to work OK in emulation mode, but I haven't tried dynarec yet.

**Comment by julliard** [comment]
> by that do you mean you trying to build wine on ARM64 with `--enable-archs=i386,x86_64.aarch64` so that the wine PE userspace is linux aarch64 (eg: wine lib folder looks like `aarch64-unix aarch64-windows i386-windows x86_64-windows`) and you are using box64 for any/all x86/x64 binary recompilation only? I couldn't get that to work with wine/box64 as it is. wine would never call box64... it juser errored whenever it met x86/x64 code

Yes, the Unix interfaces and ntdll are aarch64, the rest is x86 PE code running through emulation.

For x64 the plan is to implement ARM64EC and have basically all of Wine run as native ARM code, but the ARM64EC toolchain is not ready yet.

**Comment by Heasterian** [comment]
Small question from me. Is it going to work with wineandroid.drv?

**Comment by julliard** [comment]
> Small question from me. Is it going to work with wineandroid.drv?

It should work fine, but wineandroid.drv is pretty much abandoned at the moment, someone will have to pick it up again. Maybe emulation support will create some new motivation to maintain it...

**Pull request merged**
