### PR TITLE
add optimize build flag for Jetson orin and xavier 

### PR DESCRIPTION
**Pull request by leonpano2006**
i added optimize flags for jetson orin based device and jetson xavier based device

caution: for orin due to -mcpu=cortex-a78ae or -mcpu=cortex-a78 is not exist in gcc-10 or older
please use gcc-11 or newer, clang-16 or newer

### CODE REVIEW

**Comment by ptitSeb** [comment]
Thanks.

**Comment by leonpano2006** [comment]
> Thanks.

Is possible to provide prebuilt packages via apt for t194 and t234
For t194 have focal(jetpack 5.x) and bionic(jetpack 4.x)
For t234 have focal(jetpack 5.x) and jammy(jetpack 6.x, at time I write this, this is still beta version)

**Comment by ptitSeb** [comment]
> > Thanks.
> 
> Is possible to provide prebuilt packages via apt for t194 and t234 For t194(Jetson Xavier series) have focal(jetpack 5.x) and bionic(jetpack 4.x) For t234(jetson orin series) have focal(jetpack 5.x) and jammy(jetpack 6.x, at time I write this, this is still beta version)

I don't build apt directly on this repo, but @ryanfortner provide some. Maybe see with there if it can be done?

**Comment by leonpano2006** [comment]
> > > Thanks.
> 
> > 
> 
> > Is possible to provide prebuilt packages via apt for t194 and t234 For t194(Jetson Xavier series) have focal(jetpack 5.x) and bionic(jetpack 4.x) For t234(jetson orin series) have focal(jetpack 5.x) and jammy(jetpack 6.x, at time I write this, this is still beta version)
> 
> 
> 
> I don't build deb package directly on this repo, but @ryanfortner provide some. Maybe see with there if it can be done?

Opened in https://github.com/ryanfortner/box64-debs/issues/32

**Pull request merged**
