### PR TITLE
[X64LIBS] Updated libstdc++ and libgcc_s

### PR DESCRIPTION
**Pull request by Creeper-xie**
Now it can run Minecraft Bedrock Dedicated Server.

### CODE REVIEW

**Comment by ptitSeb** [comment]
mmm, what happened here?

**Comment by ptitSeb** [comment]
and what are those new libstdc++ and libgcc_s? I already updated those from a recent debian distro (those are from gcc 13). Were does they comes from?

**Comment by Creeper-xie** [comment]
> and what are those new libstdc++ and libgcc_s? I already updated those from a recent debian distro (those are from gcc 13). Were does they comes from?

emmmm
They come from my Ubuntu  Jammy computer.
When I tried to use the latest box64 to run Minecraft Bedrock Dedicated Server,I get an error:
Error: PltResolver: Symbol arc4random(ver 55: arc4random@GLIBC_2.36) not found, cannot apply R_X86_64_JUMP_SLOT 0x3f0024f150 (0x3f0009c2d6) in /lib/x86_64-linux-gnu/libstdc++.so.6

So I think this Error is caused by libstdc++.so.6 .I tried moving the libstdc++.so.6
 from my computer to the arm device and run Minecraft server successfully.

**Comment by ptitSeb** [comment]
that arc4random symbol is in libbsd and this should be fixed with latest box64. What is the version of your gcc on you jammy computer (`gcc --version`)

**Comment by Creeper-xie** [comment]
gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by ptitSeb** [comment]
Yeah, that's too old. I would prefer to find wht's wrong with the missing arc4random that should be found? Or found an up-to-date libstdc++ from a gcc-13 that doesn't have this dependancy.

**Comment by Creeper-xie** [comment]
I'm sorry to bother you.It's seems the old server is not suitable for the new version of libstd++ . I upgraded the server version to 1.20.41 and run with a warning 
（Warning: Global Symbol _ZTHN11ChunkSource17gPerfIsClientSideE not found, cannot apply R_X86_64_GLOB_DAT @0x107b54070 ((nil)) in /root/bds/1.20.41/bedrock_server）
It seems look ok.

**Comment by ptitSeb** [comment]
I need to re-check those libstdc++ and libgcc_s....

**Comment by strongtz** [comment]
I think I'm also running into this issue, hmm

```
info:  Game: ForzaHorizon5.exe
info:  DXVK: v2.3-15-g2ed1778df9ea5d8
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4addae0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
warn:  OpenVR: Failed to initialize OpenVR
Using emulated /sd/home/odin2/proton/GE-Proton8-23/files/lib64/wine/x86_64-unix/wineopenxr.dll.so
Using emulated /sd/home/odin2/proton/GE-Proton8-23/files/lib64/libopenxr_loader.so.1
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Warning: Global Symbol _ZN9__gnu_cxx21zoneinfo_dir_overrideEv not found, cannot apply R_X86_64_GLOB_DAT @0x7fff1024e268 ((nil)) in /lib/x86_64-linux-gnu/libstdc++.so.6
Warning: Weak Symbol _ITM_memcpyRtWn not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff1024f060 (0x9c0f6)
Look for arc4random in loaded elfs
Warning, function arc4random not found in lib libbsd.so.0
Look for arc4random in loaded elfs
Warning, function arc4random not found in lib libbsd.so.0
Look for arc4random in loaded elfs
Warning, function arc4random not found in lib libbsd.so.0
Look for arc4random in loaded elfs
Warning, function arc4random not found in lib libbsd.so.0
Error: Symbol arc4random not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff1024f150 (0x9c2d6) in /lib/x86_64-linux-gnu/libstdc++.so.6
Warning: Weak Symbol _ITM_RU1 not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff1024f6a0 (0x9cd76)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff1024fb00 (0x9d636)
Warning: Weak Symbol _ITM_RU8 not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff1024fff8 (0x9e026)
Warning: Weak Symbol _ITM_memcpyRnWt not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff102504a8 (0x9e986)
Warning: Weak Symbol _ZGTtnam not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff10250c88 (0x9f946)
Error: relocating Plt symbols in elf libstdc++.so.6
Error initializing needed lib libstdc++.so.6
Error loading one of needed lib
Error initializing needed lib libopenxr_loader.so.1
Error loading one of needed lib
Error initializing needed lib /sd/home/odin2/proton/GE-Proton8-23/files/lib64/wine/x86_64-unix/wineopenxr.dll.so
0138:err:module:open_builtin_so_file failed to load .so lib "/sd/home/odin2/proton/GE-Proton8-23/files/lib64/wine/x86_64-unix/wineopenxr.dll.so"
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Turnip Adreno (TM) 740:
info:    Driver : turnip Mesa driver 23.99.99
info:    Memory Heap[0]:
info:      Size: 8594 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x7
info:      Memory Type[1]: Property Flags = 0xf
info:      Memory Type[2]: Property Flags = 0xb
[alarm@ayn-odin2 sr]$
```

**Pull request closed without merging**
