### PR TITLE
Added new wrappings for libx11

### PR DESCRIPTION
**Pull request by mhavu**
Added some new wrappings for libx11 (including a fix for issue #272).

### CODE REVIEW

**Comment by mhavu** [comment]
Oops. Seems like #272 had already been addressed. Anyhow, this PR includes some additional new wrappings.

**Comment by mhavu** [comment]
I forgot how PRs work in GitHub, and went on to add another commit to my fork. Of course it became a part of the open PR, which was not my intention. It wouldn't be a problem, though, if the X64 Release build hadn't failed test11 for some reason. The latest commit includes a bunch of new GO wrappings for gtk, including the ones needed in fixing issue #254. However, the following missing GOM wrappings still remain:
```
GOM(gtk_tree_selection_selected_foreach, vFEpBp)
GOM(g_object_weak_ref, vFpBp)
GOM(gtk_tree_view_column_set_cell_data_func, vFEppBpB)
```

**Comment by ptitSeb** [comment]
Will you do the 3 GOM wrapping or should I do them?

**Comment by mhavu** [comment]
I'd be glad to take a stab, but I haven't found any documentation on writing GOM wrappings, so it'll take me a while to figure out what should be done. For `gtk_tree_view_column_set_cell_data_func `, it seems I could use `gtk_cell_layout_set_cell_data_func()` as an example.

**Pull request merged**
