### PR TITLE
[RV64_DYNAREC] Added more 0F MMX opcodes and some fixes

### PR DESCRIPTION
**Pull request by ksco**
for Cassette Beasts.

### CODE REVIEW

**Comment by ksco** [comment]
I just noticed the mmx test is failing.

**Comment by ksco** [comment]
The issue is caused by `MOVQ Gm, Em`, but I don't see anything wrong with it.

**Comment by ptitSeb** [comment]
How do you know it's this one? You used cosim or you disabled the opcode?

**Comment by ksco** [comment]
I disabled the opcode and it works fine. Also, the error message is [strange](https://github.com/ptitSeb/box64/actions/runs/4950119761/jobs/8853293227#step:6:124).

**Comment by ptitSeb** [comment]
when you disable an opcode, you stop a block. So it works fine maybe because of another opcodes later in the block.

**Comment by ptitSeb** [comment]
It's safer to do a "dump", using BOX64_LOAD_ADDR maybe to fix loaded address, than use BOX64_NODYNAREC=0xAAAA-0xBBBB to do a bisect on the faulty opcode

**Comment by ksco** [comment]
Yeah, I'm aware of that. I looked at block dumps and not seeing anything suspicious yet. Thanks for the advice, I'll try to debug more tomorrow.

**Comment by ksco** [comment]
I've found the issue. It's something wrong with `mmx_forget_reg`, the value of `dyn->e.mmxcache[a]` is `-1`.

**Comment by ptitSeb** [comment]
Isn't some macro to transform index to/from reg needs to be used there also?

**Comment by ksco** [comment]
Why do we need that? The 8 max regs are already 1to1 mapped, right?

**Comment by ptitSeb** [comment]
I'm not sure I'll keep the reg mapping fixed as it is. It might change in the future and maybe all regs will be allocated in a more dynamix way (except, porbably, for xmm0-xmm8 that will stay at the same place, to keep it ABI compatible).
Box64 use 24 float regs for it's cache, and the mapping of those 24regs is not linear on rv64.

**Pull request merged**
