### PR TITLE
Add missing wrappings for winewayland.so

### PR DESCRIPTION
**Pull request by strobo5**
This was a late-night attempt to fix issue #1581.

I still don't really know how the wrappings work (I should take time and learn) so I just did what seemed right. For `size_t` and `bool` I guessed how they are specified ('L' and 'c'??).

Unsuprisingly, it does not work at this point! Now there is a SIGILL during/after mapping winewayland.so.

### CODE REVIEW

**Comment by ptitSeb** [comment]
> This was a late-night attempt to fix issue #1581.
> 
> I still don't really know how the wrappings work (I should take time and learn) so I just did what seemed right. For `size_t` and `bool` I guessed how they are specified ('L' and 'c'??).
> 
> Unsuprisingly, it does not work at this point! Now there is a SIGILL during/after mapping winewayland.so.

For bool, I would use `u` instead. `c` would be signed char, I don't think it's the best approach (`C` unsigned char would be better).

For the SIGILL, it might be something else. Check if you have some `BOX64: Error, Wayland-client, add_listener to XXXX unknown, will crash soon!` in the log, that might be just that.

**Comment by strobo5** [comment]
Alriight, thanks for checking it! I'm changing the bool to `u` then.

Also I found exactly that error message. I just had to set a GDB breakpoint on that line since I still can't get the log messages printed on my terminal.

Now I'm trying to add the missing `zxdg_output_v1` listener proxy thing. It's not working yet, I'll get back later..

**Comment by ptitSeb** [comment]
Listenner are more tricky to implement. if you don't have enough example, tell me, and I'll add it.

**Comment by strobo5** [comment]
That would be great I think. This was my attempt and I don't see any obvious problems without a bit more understanding about the mechanisms.

**Comment by ptitSeb** [comment]
According to https://searchfox.org/mozilla-central/source/widget/gtk/wayland/xdg-output-unstable-v1-client-protocol.h#191 you are missing "done", vFpp, between "logical_size" and "name"

**Comment by strobo5** [comment]
Haha yes, this was it. I had seen it [here](https://wayland.app/protocols/xdg-output-unstable-v1#zxdg_output_v1:event:done), read something about "deprecated", did not see it in the winewayland.so symbols and decided to omit it.

Of course this is not how box64 works, and this Wayland listener interface..
Now I know. Sort of.

The result is that I can now start `regedit` and `winecfg`. Now I will test some games.

**Comment by ptitSeb** [comment]
thanks, and good work wrapping the listener ;)

**Comment by strobo5** [comment]
only possible with your quick feedback! thanks, this was fun

**Pull request merged**
