### PR TITLE
[RV64_DYNAREC] Fixed LOCK XCHG byte opcode

### PR DESCRIPTION
**Pull request by ksco**
A Short Hike works.

### CODE REVIEW

**Comment by ptitSeb** [comment]
is F0 86 also changed?

**Comment by ksco** [comment]
> is F0 86 also changed?

it's not yet implemented in rv64 and la64.

**Comment by ptitSeb** [comment]
> > is F0 86 also changed?
> 
> it's not yet implemented in rv64 and la64.

That's an easy copy-paste here ;)

**Comment by ksco** [comment]
> > > is F0 86 also changed?
> > 
> > 
> > it's not yet implemented in rv64 and la64.
> 
> That's an easy copy-paste here ;)

Sure but I haven't had the chance, you know something that uses this opcode?

**Pull request merged**
