### PR TITLE
[RV64_DYNAREC] Added more opcodes for SV

### PR DESCRIPTION
**Pull request by ksco**

### CODE REVIEW

**Comment by ksco** [comment]
@ptitSeb Hi, SV failed to start because of the newly added `CVTSD2SS Gx, Ex`, but what's wrong with the implementation? I don't get it, could be something wrong with the rounding mode? But the interpreter works well without handling the rounding mode. Using `BOX64_DYNAREC_TEST=1`, I saw the diff test failed with `F2 0F 5A C0 cvtsd2ss xmm0, xmm0`, but it should be any different when both operands are the same.

**Comment by ptitSeb** [comment]
The issue is that you mix `GETGX(...)` that will grab a "pseudo-register" (so only the address, purging any SS or SD register from the cache) and `GETEXSD(...)` that will load an SD register to the cache. This will conflict here when the same register is used.
I think the correct way to handle this would be:
1. use `GETEXSD(...)` to load the SD register in the cache
2. use some `GETGXSS_empty(...)` the set the register as an SS now and not an SD anymore (I might need to work on this operation)
3. convert SD2SS, it should just work after that.

There will be similar issue with other CVT operation that happens on the same register.

**Comment by ksco** [comment]
Oh, ok, make sense. I actually implemented it this way at first, see https://github.com/ptitSeb/box64/pull/700/commits/affbf8c76838c7f5c314b32313027ca87c4fdb02. But I think this way, it will zero out upper 32-bit, making the result inconsistent.

**Comment by ksco** [comment]
Ok, let me try it out, but why?

**Comment by ptitSeb** [comment]
> Ok, let me try it out, but why?

because `GETxxx_empty(...)` will mark the register as loaded, but will not try to get it's content (because `_empty`). Then `GETEXxx()` will grab the same register. Whatever happens here (recycle the register or just use it) will be wrong because the content of the register is undefined.
If you do the oposite:
`GETEXSD(..)` will load the register in a actual register, load the value. `GETGXxxx_empty(...)` should not try to read again the register because it's already loaded in memory.

Unfortunatly, what will happen here is that, because the XMM0 is in the cache as an `SD` register, and because this is `GETGXSS_empty(...)` that is used, the register will be put back in `x64emu_t`,because it's now marked as `SS`: I think I need to add a parameter to the get empty function to purge or not the register if it's a certain format already...

**Comment by ksco** [comment]
Ok, I get it now, thanks for the explanation! If we just use `GETEX` and `GETGX`, it will work also, right? But it's slower than the current way because of all the cache-purging things.

**Comment by ksco** [comment]
SV works again, this can be merged if there're no other issues. ;)

**Comment by ptitSeb** [comment]
> Ok, I get it now, thanks for the explanation! If we just use `GETEX` and `GETGX`, it will work also, right? But it's slower than the current way because of all the cache-purging things.

Yes. The `_empty(...)` getter are there to avoid unnecessary fetching of data.
And here the purging is also not usefull, even if the regs keep the value, so it works.

**Comment by ksco** [comment]
I run Stardew Valley again with `DAYNREC_LOG=1`, there're not too much of opcodes that are missing anymore really. But it still runs pretty slow. Maybe the performance of VF2 is really not enough to run this game.

**Comment by ksco** [comment]
I run SV all the way to the end of the intro, here are all the missing opcodes I collected, most of the `66 0F` ones are coming from emulated libFAudio.

```
      3 66 44 29 87 C8 01 00 00 44 8B B7 30 01 00 00
      3 66 0F 3A 0B C9 0A F2 0F 2C F9 48 8B 85 88 FE
      3 48 0F BA F0 3F 80 BB 73 01 00 00 00 74 08 48
      3 0F C8 89 43 54 8B 43 14 0F C8 89 43 58 E8 6B
      3 0F 5B CA 48 8D 04 E8 0F 59 CE 44 89 CD 66 0F
      2 F3 A6 0F 97 C0 1C 00 84 C0 74 B3 80 7D 00 00
      2 F3 A6 0F 97 C0 1C 00 84 C0 74 2E 48 89 EF 48
      2 F3 48 0F BD D6 8B FA 83 F7 3F 8B F1 C1 E6 02
      2 F0 48 01 05 BE 5B 54 00 8B 87 B8 03 00 00 F0
      2 F0 48 01 05 A5 80 54 00 49 8D 5C 24 58 48 8D
      2 F0 48 01 05 35 B6 59 00 F0 83 05 35 B6 59 00
      2 DF 6C 24 08 48 85 D2 0F 88 13 01 00 00 48 89
      2 DD 5C 24 F0 F2 0F 10 44 24 F0 66 0F 28 C8 66
      2 DB F1 72 7A DD D9 DD D9 DD 5C 24 08 F2 0F 10
      2 D8 F1 DF 6C 24 08 48 85 F6 0F 88 E7 00 00 00
      2 8C 4F 38 48 8B 14 24 89 57 44 48 8D 54 24 10
      2 66 A9 F7 FF 0F 85 DD 00 00 00 0F B7 53 12 8B
      2 66 8B 77 04 66 89 70 14 48 8D BB 58 01 00 00
      2 66 8B 47 42 66 89 44 24 20 48 8B 87 98 00 00
      2 66 45 29 7D 16 4C 8B 45 A8 45 01 F8 48 8B 45
      2 66 0F 5A F8 F3 41 0F 11 BF 10 14 00 00 0F B6
      2 66 0F 5A F0 F3 41 0F 11 B6 10 01 00 00 0F B6
      2 66 0F 5A F0 4C 01 E0 49 83 C4 78 F2 0F 10 05
      2 66 0F 5A F0 0F 14 DB 0F 5A C3 F3 0F 11 74 24
      2 66 0F 5A F0 0F 14 C9 F2 0F 10 44 24 18 0F 5A
      2 66 0F 5A E0 F3 0F 59 0D CE 05 01 00 0F 14 C9
      2 66 0F 5A E0 F3 0F 10 05 63 17 01 00 F3 0F 5E
      2 66 0F 5A E0 F2 0F 10 44 24 60 F3 0F 11 64 24
      2 66 0F 5A E0 0F 14 DB 0F 5A C3 F3 0F 11 64 24
      2 66 0F 5A C0 F3 0F 5E D9 0F 28 CA F3 42 0F 11
      2 66 0F 5A C0 F3 0F 59 4C 24 74 F3 41 0F 11 B4
      2 66 0F 5A C0 C7 44 28 F8 00 00 80 3F F3 0F 5E
      2 66 0F 5A C0 48 83 C4 18 C3 0F 1F 84 00 00 00
      2 66 0F 5A C0 42 C7 44 3D C0 00 00 00 00 42 C7
      2 66 0F 5A C0 42 C7 44 30 C0 00 00 00 00 42 C7
      2 66 0F 5A C0 41 C7 86 2C 01 00 00 00 00 00 00
      2 66 0F 3A 0B D8 09 F2 0F 2C C3 0F 57 DB F2 0F
      2 66 0F 3A 0B C0 0A F2 44 0F 2C F0 48 BF 58 56
      2 66 0F 3A 0B C0 0A F2 44 0F 2C F0 48 B8 88 55
      2 66 0F 3A 0B C0 0A F2 0F 2C D8 48 BF D0 5A 07
      2 66 0F 3A 0B C0 0A F2 0F 2C D8 48 8B BD 88 FE
      2 66 0F 3A 0B C0 0A F2 0F 2C D8 48 8B BD 88 FE
      2 48 CF 48 8D 64 24 30 5D C3 90 CC C3 66 90 55
      2 0F C8 89 45 00 8B 43 04 0F C8 89 45 04 8B 43
      2 0F C8 48 C7 84 24 18 01 00 00 00 00 00 00 0F
      2 0F C8 41 89 06 8B 43 48 0F C8 41 89 46 04 8B
      1 FE 06 EB 22 48 8D 4F 04 FF 01 C6 00 31 B9 01
      1 F3 A6 0F 97 C0 1C 00 84 C0 0F 84 57 FF FF FF
      1 F3 48 0F AE E9 48 81 EA FF 00 00 00 48 81 FA
      1 F3 48 0F AE E9 48 2D FF 00 00 00 48 3D FF 00
      1 F3 0F 51 C8 0F 2E C9 7A 04 0F 28 C1 C3 50 E8
      1 F2 0F 51 C8 66 0F 2E C9 7A 05 66 0F 28 C1 C3
      1 F0 48 01 90 D0 00 00 00 48 8B 47 10 E9 3D FF
      1 F0 48 01 90 D0 00 00 00 48 8B 44 24 70 E9 50
      1 F0 48 01 82 D0 00 00 00 48 8B 57 10 48 8B 6B
      1 DD D9 DD D9 DD 5C 24 08 F2 0F 10 44 24 08 F2
      1 C4 E3 7D 18 87 00 03 00 00 01 C4 E3 75 18 8F
      1 66 FF 07 48 8B 7B 08 44 3B 6F 08 0F 83 78 03
      1 66 FF 00 41 8B FD 44 8D 6F 01 48 8B 43 08 48
      1 66 D1 64 24 28 41 BD 08 00 00 00 8D 43 FF 4C
      1 66 0F F9 FE 66 0F EB EF 66 0F D7 FD E8 4A 79
      1 66 0F 5A E0 0F 14 DB 0F 5A C3 F3 0F 11 64 24
      1 66 0F 3A 0B C0 0A F2 0F 2C F8 41 03 FF 89 7B
      1 66 0F 16 0C D1 66 0F 58 CA 48 89 F0 48 99 48
      1 48 A1 F0 23 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 E8 20 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 E0 23 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 D8 20 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 C8 23 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 C0 20 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 98 21 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 98 1E 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 88 1E 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 60 22 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 48 22 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 20 21 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 10 21 07 1C 01 00 00 00 48 83 C0 08 C3
      1 48 A1 00 22 07 1C 01 00 00 00 48 83 C0 08 C3
      1 41 FE 09 4D 8B CA 4C 3B CE 73 25 4D 8B D0 4D
      1 41 DF 28 49 83 38 00 79 06 D8 05 9A F8 11 00
      1 37 40 80 FE 0B 74 10 48 C7 47 10 FF FF FF FF
      1 0F CF 89 3C B3 8B 7C B2 04 0F CF 89 7C B3 04
      1 0F CE 48 8B FB 48 8B 03 48 8B 40 58 FF 10 48
      1 0F CA 41 8B 69 04 44 89 E0 89 14 24 89 F1 0F
      1 0F C8 89 03 48 83 C3 04 48 83 C2 04 8D 41 FF
      1 0F C8 89 03 48 83 C3 04 48 83 C2 04 8D 41 FF
      1 0F C8 83 F9 04 72 44 89 02 83 43 18 04 5B 41
      1 0F C8 83 F9 04 72 44 89 02 83 43 18 04 5B 41
      1 0F 5B C0 0F 59 C3 0F 5B C9 0F 59 CB 0F 29 41
```

**Pull request merged**
