### PR TITLE
[RV64_DYNAREC] Fixed some found issues in vector

### PR DESCRIPTION
**Pull request by ksco**

### CODE REVIEW

**Comment by ksco** [comment]
I'm working on the CI failures.

**Comment by ksco** [comment]
BTW, dav1d works after this, but it's slower than the scalar version.

**Comment by ksco** [comment]
Oh, I got it wrong. It's already a little faster than the scalar version. There are many fallbacks to scalar cases, so it's expected.

**Comment by ptitSeb** [comment]
Yeah, speed will not be great as long as register are save / restored... Soon :D ...

**Pull request merged**
