### PR TITLE
[RV64_DYNAREC] Fixed issues caught by newly added cosim framework

### PR DESCRIPTION
**Pull request by ksco**
This is an issue found by the newly added diff test feature. ;)

### CODE REVIEW

**Comment by ksco** [comment]
@ptitSeb Run the program below with `BOX64_DYNAREC_TEST=1`, you can see that the diff check failed at `0x4000a3f67e`, which is an `IDIV` opcode, and the inconsistency is due to dividing by 0, how do we fix this?

[program.txt](https://github.com/ptitSeb/box64/files/11088281/program.txt)

**Comment by ptitSeb** [comment]
There should be a test to check if `ed` is 0 and at least jump to next if  0. That would be closer to the interpreter.
There is no divide by zero signal handling for now anyway...

**Comment by ksco** [comment]
Yeah, sure, I'll add a `BEQ`.

**Comment by ptitSeb** [comment]
I have improved the TEST_INTERPRETER, with "inter-block" handling. That means the test will follow jump now, among other things.

And a new error appeared on you test program:
```
RAX=00000000ffffffff RCX=0000000000000001 RDX=0000000000000001 RBX=0000000000000001 RSP=0000000101ffbd90 flags=??S????
RBP=0000000101ffbd90 RSI=0000000000000001 RDI=00000000ffffffff  R8=000000002121f90e  R9=00000000000300a0 
R10=0000000000000005 R11=0000000000000000 R12=00000000fffffffd R13=0000000000000001 R14=00000000fffffffd 
R15=0000000000000000 RIP=0000003fbc81a2b2 80 7D FC 00 cmp byte ptr [rbp-0x04], 0x00
RAX=00000000ffffffff RCX=0000000000000001 RDX=0000000000000001 RBX=0000000000000001 RSP=0000000101ffbd90 FLAGS=--S--P-
RBP=0000000101ffbd90 RSI=0000000000000001 RDI=00000000ffffffff  R8=000000002121f90e  R9=00000000000300a0 
R10=0000000000000005 R11=0000000000000000 R12=00000000fffffffd R13=0000000000000001 R14=00000000fffffffd 
R15=0000000000000000 RIP=0000003fbc81a2b6 78 31 js 0x0000003FBC81A2E9
Warning, difference between Interpreter and Dynarec in 0x3fbc81b020
=======================================
DIF: Dynarec |  Intepreter
----------------------
RIP: 0000003fbc81b020 | 0000003fbc81a2e9
RAX=00000000ffffffff RCX=0000000000000001 RDX=0000000000000001 RBX=0000000000000001 RSP=0000000101ffbd90 flags=??S????
RBP=0000000101ffbd90 RSI=0000000000000001 RDI=00000000ffffffff  R8=000000002121f90e  R9=00000000000300a0 
R10=0000000000000005 R11=0000000000000000 R12=00000000fffffffd R13=0000000000000001 R14=00000000fffffffd 
R15=0000000000000000 RIP=0000003fbc81b020 48 89 7D F8 mov [rbp-0x08], rdi
RAX=00000000ffffffff RCX=0000000000000001 RDX=0000000000000001 RBX=0000000000000001 RSP=0000000101ffbd90 flags=??S????
RBP=0000000101ffbd90 RSI=0000000000000001 RDI=00000000ffffffff  R8=000000002121f90e  R9=00000000000300a0 
R10=0000000000000005 R11=0000000000000000 R12=00000000fffffffd R13=0000000000000001 R14=00000000fffffffd 
```
It seems the 8bits cmp doesn't compute S flag correctly.

**Comment by ptitSeb** [comment]
Ok, found the issue on the cmp8_0, I'll push it dirrectly

**Comment by ksco** [comment]
Ok, we can merge this then, more fixes will be in another PR.

**Comment by ksco** [comment]
> There should be a test to check if ed is 0 and at least jump to next if 0.

In addition to dividing by 0, there are the following checks in the interpreter. I wonder if we just skip diff test for `IDIV`. 

```c
if (labs(quot) > 0x7fffffff) {
	INTR_RAISE_DIV0(emu);
	return;
}
```

**Comment by ptitSeb** [comment]
yeah, there is no really DIV0 handling anyway, so this can be skipped for now.

**Comment by ksco** [comment]
> Ok, found the issue on the cmp8_0, I'll push it dirrectly

Can you push that?

**Comment by ptitSeb** [comment]
I pushed it already, but it was an issue with conditionnal jump, not cmp_0, sorry.

**Comment by ksco** [comment]
The "inter-block" commit seems problematic, try the test program below, it's expected to work fine but reported several "difference" warnings after that commit.

**Comment by ptitSeb** [comment]
I have fixed some XMM issue. Note that there is still an issue with X87 Stack count / top. I need to work on that, I think it's false positive, the Dynarec doesn't refect that properly (I don't think it's much visible on RV64 yet)

**Comment by ksco** [comment]
Ack.

**Pull request merged**
