### PR TITLE
[RV64_DYNAREC] Added more support for XTheadBb extension 

### PR DESCRIPTION
**Pull request by ksco**
- Added more support for XTheadBb extension
- Added a test for bswap and movbe
- Reformatted the code this PR touches, please ignore commits named "Reformat" when reviewing.

### CODE REVIEW

**Comment by ptitSeb** [comment]
Something looks wrong, either with test24 or how movbe is handled in arm64, rv64 and interpreter!

**Comment by ksco** [comment]
Interesting, let me take a look.

**Comment by ksco** [comment]
It's the interpreter! MOVBE is operating on GPRs, not XMMs.

**Comment by ptitSeb** [comment]
Ah nice. And the ARM64 implementation seems wrong too :'(

**Comment by ksco** [comment]
One test catches all three :)

**Comment by ksco** [comment]
Fixed.

**Pull request merged**
