### PR TITLE
[TESTS] Disable compiler optimizations for test17 and some related fixes

### PR DESCRIPTION
**Pull request by ksco**

### CODE REVIEW

**Comment by ksco** [comment]
Oh ARM counterparts are failing probably for the same reason too, but I know nothing about ARM..

**Comment by ptitSeb** [comment]
How did you regereate the ref17.txt?

**Comment by ksco** [comment]
I run it in an x86-64 native machine with `./test17 > ref17.txt`.

**Comment by ptitSeb** [comment]
ok, then there is a issue with dynarec or interpreter for subpd. I probably didn't added some of the nan test to this one I suppose.

**Comment by ksco** [comment]
It's probably something off with `maxsd/minsd`, and I've fixed the issue in RISC-V and interpreter counterparts.

**Comment by ksco** [comment]
"If the values being compared are both 0.0s (of either sign), the value in the second source operand is returned." 
https://www.felixcloutier.com/x86/maxsd

We didn't deal with this case before, it probably happened to be optimized by gcc.

**Comment by ptitSeb** [comment]
I'll merge and fix it afterward...

**Comment by ptitSeb** [comment]
So, yeah, the issue in the MINSD/MAXSD test with 0 / -0 that should copy the arg.
TBH, It will add a lot of code and I'm not sure it's usefull in real life stuff

**Comment by ksco** [comment]
Yeah it is probably not so useful, but we need to pass that test.

**Comment by ptitSeb** [comment]
bah, I found an easy way to do it, tests are green for me locally.

**Comment by ksco** [comment]
A clever trick!

**Comment by ptitSeb** [comment]
same could probably be used on rv64 too, to avoid specific test of 0 value

**Comment by ksco** [comment]
Let me try it out.

**Pull request merged**
