### PR TITLE
[RV64_DYNAREC] Add more opcodes for SV

### PR DESCRIPTION
**Pull request by ksco**
Haven't tested with SV yet but I will do the test tomorrow.

### CODE REVIEW

**Comment by ptitSeb** [comment]
Ok, I'll wait until tomorrow to merge then.

I also noticed that WorldOfGoo doesn't work anymore, I need to debug that.

**Comment by ksco** [comment]
Ok, I've tested it, still works.

**Comment by ptitSeb** [comment]
> Ok, I've tested it, still works.

Yeah, I just forgot to not use system SDL2 when I launch it. It launch, and is playable also.

**Comment by ksco** [comment]
Oh, I mean I've done the regression with Stardew Valley, but still good news on World of Goo, I'll try it later for sure.

**Comment by ptitSeb** [comment]
Yeah, I was't sure... Eiher way, I merged the PR ;)

**Pull request merged**
