### PR TITLE
[CI] Add Android Tests

### PR DESCRIPTION
**Pull request by KreitinnSoftware**

### CODE REVIEW

**Comment by ptitSeb** [comment]
Nice, but some tests are not passing.

**Comment by KreitinnSoftware** [comment]
Test07 and Test17 works fine on Android x86_64 and on Box64 bugs
Test11 needs fixes for android, even on Android x86_64 get pthread error

**Comment by ptitSeb** [comment]
Then disable the test for now, to be re-enable later, and have the test green.

**Comment by KreitinnSoftware** [comment]
> Then disable those tests for now, to be re-enable later, and have the test green.

Okay

**Comment by mcagabe19** [comment]
@KreitinnSoftware if possible can u add TERMUX testing too? (it uses ANDROID flag TERMUX is just ex flag for termux builds and u can use [termux-docker](https://github.com/termux/termux-docker) for a vm)

**Comment by KreitinnSoftware** [comment]
> @KreitinnSoftware if possible can u add TERMUX testing too? (it uses ANDROID flag TERMUX is just ex flag for termux builds and u can use [termux-docker](https://github.com/termux/termux-docker) for a vm)

It's only use the same environment that android tests (since termux build it's android build with some flags different)

**Comment by KreitinnSoftware** [comment]
> @KreitinnSoftware if possible can u add TERMUX testing too? (it uses ANDROID flag TERMUX is just ex flag for termux builds and u can use [termux-docker](https://github.com/termux/termux-docker) for a vm)

I will see

**Comment by mcagabe19** [comment]
@KreitinnSoftware you forget `-DTERMUX=1` in termux builds

**Comment by mcagabe19** [comment]
please see docs correctly

**Comment by KreitinnSoftware** [comment]
For some reason, on last commit simply stuck on Env Preparation on Termux Builds...

**Comment by KreitinnSoftware** [comment]
I will fix it later

**Comment by KreitinnSoftware** [comment]
I don't understand why it didn't recognize the lib

**Comment by KreitinnSoftware** [comment]
> I don't understand why it didn't recognize the lib

On my PC with same qemu, same version of the lib works

**Comment by KreitinnSoftware** [comment]
In this last commit worked, but for some reason test05 failed, but testing in my pc or in trace version of this build worked fine, I guess it's a qemu fault, I will submit another workflow to see

**Comment by ptitSeb** [comment]
Thanks, that will help make android/termux build more stable.

**Pull request merged**
