### PR TITLE
[LA64_DYNAREC] Not codegen native_lock_write_b or native_lock_xchg_b node for  not support AMCAS or AMBH platform (#2053)

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi,

Testcase Passed:

```
./build/box64 /yourpath/jdk-23/bin/java -version

Box64 with Dynarec v0.3.1  built on Nov 21 2024 14:47:04
Warning, of_unconvert(...) left over 0x8000, converted 0x8402
Warning, of_unconvert(...) left over 0x8000, converted 0x8402
Warning, of_unconvert(...) left over 0x8000, converted 0x8402
openjdk version "23.0.1" 2024-10-15
OpenJDK Runtime Environment Zulu23.30+13-CA (build 23.0.1+11)
OpenJDK 64-Bit Server VM Zulu23.30+13-CA (build 23.0.1+11, mixed mode)
```

Please review my patch.

Thanks,
Leslie Zhai

### CODE REVIEW

**Comment by ptitSeb** [comment]
Using the mutex path on the interpreter is not the solution. It will break when Interpreter and Dynarec are running simulatneously.

**Review by ptitSeb — CHANGES_REQUESTED** [review]
Not the solution. The mutex path is for Interpreter only build, no exeptions.

**Comment by ksco** [comment]
> maybe writting the missing F0 opcode would help?

Oh it's a missing opcode? I was wondering why it fallbacks to the interpreter...

**Comment by ksco** [comment]
Closed as this is not a solution.

**Pull request closed without merging**
