### PR TITLE
[LA64_DYNAREC] Added MOVLPD and MOVHPD opcodes

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi,

Please review my patch.

Thanks,
Leslie Zhai

### CODE REVIEW

**Review by ksco — CHANGES_REQUESTED** [review]
I don't think `MOVLPD` and `MOVHPD` share exactly the same implementation, please refer to x86 specification.

**Comment by xiangzhai** [comment]
Fixed VSTELM_D wrong idx compared with VPICKVE2GR_D hi64 and lo64:
```
   0xfff6aed5c8:    addi.d    $r6,$r12,16(0x10)
   0xfff6aed5cc:    vpickve2gr.d    $r7,$vr2,0x1 ; hi64
(gdb) i r $vr2
vr2            {v16i8 = {0x6e, 0x50, 0xc8, 0xe7, 0x88, 0xe4, 0x68, 0x40, 0xfc, 0x40, 0x9d, 0xd3, 0x5e, 0x26, 0xe9, 0x3f}, v8i16 = {0x506e, 0xe7c8, 0xe488, 0x4068, 0x40fc, 0xd39d, 0x265e, 0x3fe9}, v4i32 = {0xe7c8506e, 0x4068e488, 0xd39d40fc, 0x3fe9265e}, v2i64 = {0x4068e488e7c8506e, 0x3fe9265ed39d40fc}, v4f32 = {0x0, 0x3, 0x7e080000, 0x1}, v2f64 = {0xc7, 0x0}}
(gdb) i r $r7
r7             0x3fe9265ed39d40fc  4605254282682122492
   0xfff6aed5d0:    vpickve2gr.d    $r7,$vr2,0x0 ; lo64
(gdb) i r $r7
r7             0x4068e488e7c8506e  4641210692660645998
   0xfff6aed5d4:    vstelm.d    $vr2,$r6,0,0x1   ; hi64
   0xfff6aed5d8:    ld.d    $r7,$r6,0
(gdb) i r $r7
r7             0x3fe9265ed39d40fc  4605254282682122492
   0xfff6aed5dc:    0x00368c05
...
```

Thanks,
Leslie Zhai

**Review by ksco — APPROVED** [review]
There is nothing to compare, the “fix” in commit https://github.com/ptitSeb/box64/commit/241052b3f2b1a6b6d2a2339dafb3eabc56f4a1fd is wrong.

Anyway, PR looks good now.

**Comment by xiangzhai** [comment]
> There is nothing to compare, the “fix” in commit 241052b is wrong.

Sorry for drunk coding.

Thanks,
Leslie Zhai

**Comment by ksco** [comment]
@ptitSeb this can be merged now

**Comment by xiangzhai** [comment]
@ptitSeb Merry Christmas 🎄 Happy New Year 🍻

**Comment by ptitSeb** [comment]
> @ptitSeb Merry Christmas 🎄 Happy New Year 🍻

Thank you. Happy new year to you too

**Pull request merged**
