### PR TITLE
[RV64_DYNAREC] Extended simple wrapper for more int types

### PR DESCRIPTION
**Pull request by xctan**

### CODE REVIEW

**Review by ksco — APPROVED** [review]

**Comment by ptitSeb** [comment]
How is the speed increase?

**Comment by xctan** [comment]
> How is the speed increase?

Tested on Banana Pi BPI-F3:

| test case | before new register mapping | now |
| -- | -- | -- |
| `getpid()` | 1140444 calls/s | 1293757 calls/s |
| `free(NULL)` | 15438979 call/s | 19245900 call/s |

**Comment by ptitSeb** [comment]
not bad

**Comment by ksco** [comment]
The improvements might be diluted for functions tend to do more, but it's nice to have anyway.

**Pull request merged**
