### PR TITLE
Added syscall 82 (for #88)

### PR DESCRIPTION
**Pull request by nniro**

### CODE REVIEW

**Review by ptitSeb — COMMENTED** [review]
You should also create the direct wrap line 119, for the build where __NR_rename does exist

**Comment by ptitSeb** [comment]
Thanks, nice!

**Comment by nniro** [comment]
Yeah, I added the part on line 119 at first but then I wasn't sure because __NR_rename would give out an error at compile time (so it really needs the macro conditional).

**Comment by nniro** [comment]
Thank you for writing such a nice project! 

Merci beaucoup, c'est super de pouvoir faire rouler des jeux sur ARM! :D

**Comment by ptitSeb** [comment]
De rien :)

(asciisec fait partie de ma "liste de jeux à tester regulièrement", mais je ne joue pas. je fait juste un nouveau jeux et je quite :( )

**Pull request merged**
