### PR TITLE
[RV64_DYNAREC] Added more 66 0F opcodes for vector

### PR DESCRIPTION
**Pull request by ksco**

### CODE REVIEW

**Comment by ptitSeb** [comment]
All red on the CI! The sse tests all failed.

**Comment by ksco** [comment]
yeah sorry, it fails with vlen=256 on the newly added `packuswb`, I've only handled and tested vlen=128, need to think about another way... :(

**Comment by ptitSeb** [comment]
Well, you can keep the method for when vlen>=256 anyway, and put a method when vlen=128 by spiliting the operation in 2 64bits expensions...

**Comment by ksco** [comment]
fixed vlen>=256 cases above, 3 more instructions are needed. the `packuswb` opcode is tricky because we use the narrowing instruction `vnclipu.wv`, which doubles the LMUL on source registers (i.e. 2 registers form a group). but if vlen>=256, there is no need for a register group....

**Comment by ptitSeb** [comment]
Strange that vlen>=256 needs more opcodes then shorter vlen... But ok.

**Pull request merged**
