### PR TITLE
Add SDL_RenderGeometryRaw wrapped function to SDL2

### PR DESCRIPTION
**Pull request by DragonSWDev**
This function is used by Dear ImGui ([imgui_impl_sdlrenderer2.cpp](https://github.com/ocornut/imgui/blob/6982ce43f5b143c5dce5fab0ce07dd4867b705ae/backends/imgui_impl_sdlrenderer2.cpp#L202)) in SDL_Renderer implementation. Adding this fixed my simple SDL2 game that uses SDL_Renderer and Dear ImGUI for interface. Seems to work fine.

### CODE REVIEW

**Review by ksco — APPROVED** [review]
LGTM

**Comment by ksco** [comment]
So CI failed, please submit the generated files too. (Those file will be generated after `make`.)

**Comment by DragonSWDev** [comment]
@ksco Sorry, I omitted them accidentally, should be good now.

**Comment by ptitSeb** [comment]
Ok, merged.

**Pull request merged**
