### PR TITLE
[DYNAREC_RV64] Added more opcodes for VMP-protected GI

### PR DESCRIPTION
**Pull request by xctan**
66 0F BD BSR seems to trigger some unknown bugs in other opcodes.

### CODE REVIEW

**Comment by ptitSeb** [comment]
> 66 0F BD BSR seems to trigger some unknown bugs in other opcodes.

So it ready to merge or shall I wait?

**Comment by xctan** [comment]
Ready to merge. VMP should entirely run inside dynarec after this PR, but I'm unsure whether the hidden bug can be found in a few days.

**Comment by ptitSeb** [comment]
Ok.

**Comment by xctan** [comment]
The bug is that VMP cannot generate a meaningful anti-debugger message but garbages (so still having problem with debugger check).

**Pull request merged**
