### PR TITLE
[LA64_DYNAREC] Added AES opcodes

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi,

Please review my patch.

Thanks,
Leslie Zhai

### CODE REVIEW

**Review by ksco — CHANGES_REQUESTED** [review]
RV64 implementations does not always apply to LA64, I believe there is no need to do this while you have LSX at hand.

**Comment by ksco** [comment]
Check how ARM64 did it, and adapt it to LA64.

**Review by ksco — APPROVED** [review]
Better.

**Comment by xiangzhai** [comment]
Thanks!

**Pull request merged**
