### PR TITLE
[RV64_DYNAREC] Added more opcodes

### PR DESCRIPTION
**Pull request by LiZhuoheng-coder**

### CODE REVIEW

**Review by ksco — COMMENTED** [review]
Looks good, but this is again mixed spaces and tabs. I know it's boring stuff and I really hate to point it out again. Maybe you should check your text editor settings. Mixed spaces and tabs is not a good idea in general anyway.

**Comment by LiZhuoheng-coder** [comment]
> Looks good, but this is again mixed spaces and tabs. I know it's boring stuff and I really hate to point it out again. Maybe you should check your text editor settings. Mixed spaces and tabs is not a good idea in general anyway.

I still use git clang-format

**Comment by LiZhuoheng-coder** [comment]
> Looks good, but this is again mixed spaces and tabs. I know it's boring stuff and I really hate to point it out again. Maybe you should check your text editor settings. Mixed spaces and tabs is not a good idea in general anyw

**Comment by ksco** [comment]
Then it's 100% sure you are not using the clang-format correctly.

**Review by ksco — APPROVED** [review]

**Pull request closed without merging**
