### PR TITLE
[RV64_DYNAREC] Detect vector extension

### PR DESCRIPTION
**Pull request by ksco**
Dynarec for RISC-V With extension: I M A F D C Zba Zbb Zbc Zbs Vector PageSize:4096 Running on Spacemit(R) X60 with 8 Cores

### CODE REVIEW

**Comment by ptitSeb** [comment]
We might want to check if it's v0.7 or v1.0 extension?

**Comment by ksco** [comment]
> We might want to check if it's v0.7 or v1.0 extension?

Yeah this checks, there is no vcsr in v0.7.

**Comment by ptitSeb** [comment]
ok, but what if we want to support v0.7? there is a lot of harsware out there with 0.7

**Comment by ksco** [comment]
I'm thinking of adding v1.0 first, then adapting the code to v0.7.1 (or xtheadvector for its new name) if necessary.

**Comment by ptitSeb** [comment]
Ok, I wont be abble to help you there, I don't have any v1.0 copliant hardware.

**Pull request merged**
