### PR TITLE
[SDORYON1] Oryon1 (Snapdragon Elite) support

### PR DESCRIPTION
**Pull request by powpingdone**
Some compiler flags for the Oryon1 support. I still need to test this. I don't believe that this cpu has 32 bit support, though I'm not 100% sure.

### CODE REVIEW

**Comment by ptitSeb** [comment]
There is no 32bits support in Oryon1 CPU Cores.

**Comment by powpingdone** [comment]
That's kinda what I figured, but I didn't find a solid source anywhere.

**Comment by ptitSeb** [comment]
That's a trending with new chips anyway. Cortex X, M1, Oryon... All have droped the 32bits support to save some silicon.

Side note, the official naming is "X", with 2 derivative: X-Elite and X-Plus.

**Comment by powpingdone** [comment]
If you're talking about the `X1E` naming stuff, I'll go ahead and modify it to be something more readable.

**Comment by powpingdone** [comment]
I'm sorry that I have to ask this, but what's the best way to test these flags for compatibility?

**Comment by ptitSeb** [comment]
> I'm sorry that I have to ask this, but what's the best way to test these flags for compatibility?

What do you mean? Testing if the binary build and run on an X-Elite/X-Plus laptop running linux?

**Comment by powpingdone** [comment]
Yeah, kinda. Making sure I don't run into instructions that aren't in the CPU. I might have blown away my previous Gentoo install with these compiler flags, even though I copied them from the GCC repo.

**Comment by powpingdone** [comment]
It does pass the test suite with `-fsanitize={undefined,address}` and no sanitizer, so it might be ok.

**Comment by powpingdone** [comment]
I'm going to presume if it passes the tests, then it's "ok."

**Comment by ptitSeb** [comment]
looks good to me. I'll try to test later (tomorrow?)

**Pull request merged**
